input_file_name: "/data/lbariogl/flow/LHC23_PbPb_pass3_new/alternative/AO2D_merged.root"

input_file_AR_name: "/data/lbariogl/flow/LHC23_PbPb_pass3_new/alternative/AnalysisResults_merged.root"

resolution_file_name: "resolution_Qvec.root"

output_dir_name: "../results_pass3_new_alternative/"
output_file_name: "flow.root"
output_file_name_qc: "qc.root"

nuclei_tree_name: "O2nucleitable"
ep_tree_name: "O2nucleitableflow"

mandatory_selections: "fSign < 0 and abs(fEta) < 0.8"
selection_dict : {
  "abs(fDCAxy)" : "abs(fDCAxy) < 0.1",
  "abs(fDCAz)": "abs(fDCAz) < 1.",
  "fTPCnCls": "fTPCnCls > 99"
}
ptdep_selection_dict : {
  "fAvgItsClusSizeCosLambda" : ["fAvgItsClusSizeCosLambda > 6",
                                "fAvgItsClusSizeCosLambda > 5.5",
                                "fAvgItsClusSizeCosLambda > 5.5",
                                "fAvgItsClusSizeCosLambda > 5",
                                "fAvgItsClusSizeCosLambda > 5",
                                "fAvgItsClusSizeCosLambda > 5",
                                "fAvgItsClusSizeCosLambda > 5",
                                "fAvgItsClusSizeCosLambda > 5"]
}

centrality_classes: [[0, 10], [10, 20], [20, 40], [40, 60]]
pt_bins: [
  [2, 2.4, 2.8, 3.2, 4., 4.8, 5.6, 6.4, 7.2],
  [2, 2.4, 2.8, 3.2, 4., 4.8, 5.6, 6.4, 7.2],
  [2, 2.4, 2.8, 3.2, 4., 4.8, 5.6, 6.4, 7.2],
  [2., 2.4, 2.8, 3.2, 4., 4.8, 6.]
]
cent_colours: [633, 797, 418, 862]

cent_detector_label: "FT0C"
reference_flow_detector: "FT0C"

use_Barlow: True

p_train: [-321.34, 0.6539, 1.591, 0.8225, 2.363]
resolution_train: 0.09
n_sigma_plot: 5

do_syst: False
n_trials: 500

cut_dict_syst: {
  "abs(fDCAxy)": {"cut_greater": False, "cut_list": [0.05, 0.15, 11]},
  "abs(fDCAz)": {"cut_greater": False, "cut_list": [0.75, 1.00, 26]},
  "fTPCnCls": {"cut_greater": True, "cut_list": [100, 130, 7]}
}

ptdep_cut_dict_syst: {
  "fAvgItsClusSizeCosLambda" : [{"cut_greater": True, "cut_list": [5.5, 6.5, 11]},
                                {"cut_greater": True, "cut_list": [5., 6., 11]},
                                {"cut_greater": True, "cut_list": [5., 6., 11]},
                                {"cut_greater": True, "cut_list": [4.5, 5.5, 11]},
                                {"cut_greater": True, "cut_list": [4.5, 5.5, 11]},
                                {"cut_greater": True, "cut_list": [4.5, 5.5, 11]},
                                {"cut_greater": True, "cut_list": [4.5, 5.5, 11]},
                                {"cut_greater": True, "cut_list": [4.5, 5.5, 11]}]
}
